### ISSUE TITLE
"JavaScript Modules" Guide example not building 

### ISSUE THREAD

**Issue by VictorBjelkholm** [clojure/clojurescript-site#143]
The guide published at https://clojurescript.org/guides/javascript-modules seems to be slightly incorrect as it doesn't build currently.

Tried integrating a JavaScript library in a project of mine but was getting errors so thought I would put together a minimal reproducible case to get help with.

So, upon finding this guide, I copied and pasted it literally, but that won't build either.

Full error:

```                                                                                                                                                                                                     $ lein trampoline run -m clojure.main watch.clj
Building ...
WARNING: JavaScript file found on classpath for library `js.hello`, but does not contain a corresponding `goog.provide` declaration: file:/data/projects/victorbjelkholm/hello-es6/src/js/hello.js
Reading analysis cache for jar:file:/home/victor/.m2/repository/org/clojure/clojurescript/1.9.854/clojurescript-1.9.854.jar!/cljs/core.cljs
Compiling src/hello_es6/core.cljs
Reading analysis cache for jar:file:/home/victor/.m2/repository/org/clojure/clojurescript/1.9.854/clojurescript-1.9.854.jar!/cljs/nodejs.cljs
WARNING: JavaScript file found on classpath for library `js.hello`, but does not contain a corresponding `goog.provide` declaration: file:/data/projects/victorbjelkholm/hello-es6/src/js/hello.js
clojure.lang.ExceptionInfo: failed compiling file:src/hello_es6/core.cljs {:file #object[java.io.File 0x5457123a "src/hello_es6/core.cljs"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at cljs.compiler$compile_file$fn__4440.invoke(compiler.cljc:1521)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1482)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1458)
	at cljs.closure$compile_file.invokeStatic(closure.clj:533)
	at cljs.closure$compile_file.invoke(closure.clj:524)
	at cljs.closure$eval6681$fn__6682.invoke(closure.clj:602)
	at cljs.closure$eval6617$fn__6618$G__6606__6625.invoke(closure.clj:486)
	at cljs.closure$compile_sources$iter__6805__6809$fn__6810.invoke(closure.clj:947)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:703)
	at clojure.core$next__6406.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3115)
	at clojure.core$doall.invokeStatic(core.clj:3121)
	at clojure.core$doall.invoke(core.clj:3121)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:943)
	at cljs.closure$compile_sources.invoke(closure.clj:932)
	at cljs.closure$build.invokeStatic(closure.clj:2528)
	at cljs.closure$build.invoke(closure.clj:2444)
	at cljs.closure$watch$buildf__7486.invoke(closure.clj:2647)
	at cljs.closure$watch.invokeStatic(closure.clj:2679)
	at cljs.closure$watch.invoke(closure.clj:2623)
	at cljs.build.api$watch.invokeStatic(api.clj:219)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:216)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:210)
	at cljs.build.api$watch.invoke(api.clj:207)
	at user$eval7609.invokeStatic(watch.clj:3)
	at user$eval7609.invoke(watch.clj:3)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$script_opt.invokeStatic(main.clj:337)
	at clojure.main$script_opt.invoke(main.clj:332)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at user$eval15.invokeStatic(form-init4692376554675479651.clj:1)
	at user$eval15.invoke(form-init4692376554675479651.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: js.hello, could not locate js/hello.cljs, js/hello.cljc, or JavaScript source providing "js.hello" in file src/hello_es6/core.cljs {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:694)
	at cljs.analyzer$error.invoke(analyzer.cljc:690)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:692)
	at cljs.analyzer$error.invoke(analyzer.cljc:690)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2111)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2085)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3430)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3425)
	at cljs.analyzer$analyze_STAR_$fn__3152.invoke(analyzer.cljc:3547)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6703)
	at clojure.core$reduce.invoke(core.clj:6686)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3547)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3537)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3571)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3554)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1340)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1319)
	at cljs.compiler$compile_file_STAR_$fn__4409.invoke(compiler.cljc:1425)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1226)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1215)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1410)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1403)
	at cljs.compiler$compile_file$fn__4440.invoke(compiler.cljc:1507)
	... 70 more

Watching paths: /data/projects/victorbjelkholm/hello-es6/src
```

**Comment by kevinjamescasey** [comment]
A newer version of Clojurescript works.
https://stackoverflow.com/questions/45886271/why-does-the-javascript-modules-guide-example-not-work

I suspect it would be best to just update the guide with the newer version so more people don't get stuck at the problem.  I'll try to make a PR for it

**Comment by VictorBjelkholm** [comment]
thanks @kevinjamescasey!

I can confirm that changing from version `1.9.854` to `1.9.908` and also adding `:optimizations :advanced` to `watch.clj` does fix the issue 👍

**Comment by tow8ie** [comment]
It’s broken again with ClojureScript version `1.9.946`:

```
WARNING: JavaScript file found on classpath for library `js.hello`, but does not contain a corresponding `goog.provide` declaration: file:/......./hello-es6/src/js/hello.js
module.js:471
    throw err;
    ^

Error: Cannot find module '@cljs-oss/module-deps'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:3:13
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)

Reading analysis cache for jar:file:/....../.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/core.cljs
Compiling src/hello_es6/core.cljs
Reading analysis cache for jar:file:/......../.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/nodejs.cljs
WARNING: JavaScript file found on classpath for library `js.hello`, but does not contain a corresponding `goog.provide` declaration: file:/........./hello-es6/src/js/hello.js
clojure.lang.ExceptionInfo: failed compiling file:src/hello_es6/core.cljs {:file #object[java.io.File 0xae20523 "src/hello_es6/core.cljs"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at cljs.compiler$compile_file$fn__4466.invoke(compiler.cljc:1552)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1513)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1489)
	at cljs.closure$compile_file.invokeStatic(closure.clj:540)
	at cljs.closure$compile_file.invoke(closure.clj:531)
	at cljs.closure$eval6721$fn__6722.invoke(closure.clj:609)
	at cljs.closure$eval6657$fn__6658$G__6646__6665.invoke(closure.clj:493)
	at cljs.closure$compile_sources$iter__6845__6849$fn__6850.invoke(closure.clj:954)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:703)
	at clojure.core$next__6406.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3115)
	at clojure.core$doall.invokeStatic(core.clj:3121)
	at clojure.core$doall.invoke(core.clj:3121)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:950)
	at cljs.closure$compile_sources.invoke(closure.clj:939)
	at cljs.closure$build.invokeStatic(closure.clj:2596)
	at cljs.closure$build.invoke(closure.clj:2507)
	at cljs.closure$watch$buildf__7525.invoke(closure.clj:2715)
	at cljs.closure$watch.invokeStatic(closure.clj:2747)
	at cljs.closure$watch.invoke(closure.clj:2691)
	at cljs.build.api$watch.invokeStatic(api.clj:219)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:216)
	at cljs.build.api$watch.invoke(api.clj:207)
	at cljs.build.api$watch.invokeStatic(api.clj:210)
	at cljs.build.api$watch.invoke(api.clj:207)
	at user$eval7648.invokeStatic(watch.clj:3)
	at user$eval7648.invoke(watch.clj:3)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$script_opt.invokeStatic(main.clj:337)
	at clojure.main$script_opt.invoke(main.clj:332)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at user$eval15.invokeStatic(form-init15357127650523017785.clj:1)
	at user$eval15.invoke(form-init15357127650523017785.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: js.hello, could not locate js/hello.cljs, js/hello.cljc, or JavaScript source providing "js.hello" in file src/hello_es6/core.cljs {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
	at cljs.analyzer$error.invoke(analyzer.cljc:693)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:695)
	at cljs.analyzer$error.invoke(analyzer.cljc:693)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2128)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2102)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3467)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3462)
	at cljs.analyzer$analyze_STAR_$fn__3177.invoke(analyzer.cljc:3586)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6703)
	at clojure.core$reduce.invoke(core.clj:6686)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3586)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3576)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3610)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3593)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1377)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1356)
	at cljs.compiler$compile_file_STAR_$fn__4435.invoke(compiler.cljc:1456)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1271)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1260)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1441)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1434)
	at cljs.compiler$compile_file$fn__4466.invoke(compiler.cljc:1538)
	... 70 more
```

**Comment by theronic** [comment]
Any luck with this? I'm seeing the same `does not contain a corresponding `goog.provide` declaration` for various libraries

**Comment by VictorBjelkholm** [comment]
Closing this as https://github.com/clojure/clojurescript-site/pull/145 was merged. Thanks @kevinjamescasey

**Comment by prees1** [comment]
I am also seeing the same error in version `1.9.946`, merge #145 was set the version to `1.9.908`. Is it fair to say this is an issue again?

**Comment by ChillkroeteTTS** [comment]
Just if somebody stumbles over this post and wants a dirty fix:
Installing @cljs-oss/module-deps via npm fixed it for me.

**Comment by attentive** [comment]
Just adding my vote to the above from @ChillkroeteTTS, I had this issue with a Figwheel build today and 

`yarn add @cljs-oss/module-deps`

fixed it with ease after quite a long search for a "proper" fix.
